#include<bits/stdc++.h>
using namespace std;

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
 
// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

char diffChar(string s,string t){
    unordered_map<char,int>freq;
    for(int i=0;i<s.size();i++){
        freq[s[i]]++;
    }
    for(int i=0;i<t.size();i++){
        if(freq.find(t[i])==freq.end())return t[i];
        freq[t[i]]--;
    }
    return 'a';
}

int main(){
    string s="sdfs", t="fsdsw";
    cout<<diffChar(s,t);
}